let lessons = [
  {
    id: 1001,
    title: "Math",
    location: "London",
    quantity: 5,
    price: 300,
    image: "images/math.png",
    rating: 5,
    show: true,
  },
  {
    id: 1002,
    title: "Science",
    location: "Dubai",
    quantity: 5,
    price: 130,
    image: "images/science.png",
    rating: 5,
    show: true,
  },
  {
    id: 1003,
    title: "SST",
    location: "London",
    quantity: 5,
    price: 20,
    image: "images/SST.png",
    rating: 1,
    show: true,
  },
  {
    id: 1004,
    title: "Mobile Dev",
    location: "London",
    quantity: 5,
    price: 120,
    image: "images/mobile.png",
    rating: 4,
    show: true,
  },
  {
    id: 1005,
    title: "Web Dev",
    location: "London",
    quantity: 5,
    price: 212,
    image: "images/web.png",
    rating: 4,
    show: true,
  },
  {
    id: 1006,
    title: "English",
    location: "Kerala",
    quantity: 5,
    price: 300,
    image: "images/english.png",
    rating: 5,
    show: true,
  },
  {
    id: 1007,
    title: "Law",
    location: "London",
    quantity: 5,
    price: 100,
    image: "images/law.png",
    rating: 5,
    show: true,
  },
  {
    id: 1008,
    title: "Dance",
    location: "Dubai",
    quantity: 5,
    price: 201,
    image: "images/dance.png",
    rating: 1,
    show: true,
  },
  {
    id: 1009,
    title: "Music",
    location: "Dubai",
    quantity: 5,
    price: 105,
    image: "images/music.png",
    rating: 4,
    show: true,
  },
  {
    id: 10010,
    title: "Cartography ",
    location: "Hogwarts",
    quantity: 5,
    price: 224,
    image: "images/mapping.png",
    rating: 4,
    show: true,
  },
  {
    id: 10011,
    title: "French ",
    location: "Hogwarts",
    quantity: 5,
    price: 200,
    image: "images/french.png",
    rating: 4,
    show: true,
  },
];
